export const ROLES = ['super_admin', 'admin', 'manager', 'team_lead', 'employee'];
export const ROLE_LABEL = { super_admin: 'Super Admin', admin: 'Admin', manager: 'Project Manager', team_lead: 'Team Lead', employee: 'Employee' };
export const PROJECT_STATUSES = ['planning', 'active', 'on_hold', 'completed', 'cancelled'];
export const TASK_STATUSES = ['todo', 'in_progress', 'in_review', 'blocked', 'done'];
export const PRIORITIES = ['low', 'medium', 'high', 'critical'];
export const TASK_TYPES = ['feature', 'bug', 'improvement', 'research', 'documentation', 'testing'];
export const CLIENT_STATUSES = ['prospect', 'active', 'inactive'];
export const BILLING_TYPES = ['fixed_price', 'time_and_material', 'retainer'];
export const RISK_LEVELS = ['low', 'medium', 'high'];
export const MODULE_STATUSES = ['not_started', 'in_progress', 'completed', 'on_hold'];
export const INDUSTRIES = ['IT / Software', 'Banking & Finance', 'Healthcare', 'Manufacturing', 'Retail & E-commerce', 'Education', 'Logistics', 'Real Estate', 'Telecom', 'Government', 'Media', 'Other'];
export const label = (s) => String(s || '').replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
